import type { Metadata } from "next";
import "./globals.css";
import { Dancing_Script } from 'next/font/google';

// Configuração da fonte Quicksand
const quicksand = Dancing_Script({
  weight: "400", // ou outros pesos que você desejar
  variable: "--font-quicksand",
  subsets: ['latin'],
  display: "swap",
  style: "normal",
});

export const metadata: Metadata = {
  title: "Portfolio CIEE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${quicksand.variable} antialiased`} // Correção da variável da fonte
      >
        {children}
      </body>
    </html>
  );
}
